
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class FrameInsereCartao extends javax.swing.JFrame {
    Cartao cartao = new Cartao();
    /**
     * Creates new form FrameInsereCartao
     */
    public FrameInsereCartao() {
        initComponents();
        setResizable(false);  //NAO DEIXA REDIMENSIONAR
        setLocation(220, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCartao = new javax.swing.ButtonGroup();
        grupoCPF = new javax.swing.ButtonGroup();
        panelInsereCartao = new javax.swing.JPanel();
        lbInserirCartao = new javax.swing.JLabel();
        panelCartaoInserido = new javax.swing.JPanel();
        lbCartaoInserido = new javax.swing.JLabel();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();
        panelCPF = new javax.swing.JPanel();
        rbCPFNao = new javax.swing.JRadioButton();
        rbCPFSim = new javax.swing.JRadioButton();
        lbNotaFiscalPaulista = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        ftfCPF = new javax.swing.JFormattedTextField();
        panelConfirmar = new javax.swing.JPanel();
        btConfirmar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInsereCartao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbInserirCartao.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbInserirCartao.setText("Inserir Cartao");

        javax.swing.GroupLayout panelInsereCartaoLayout = new javax.swing.GroupLayout(panelInsereCartao);
        panelInsereCartao.setLayout(panelInsereCartaoLayout);
        panelInsereCartaoLayout.setHorizontalGroup(
            panelInsereCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsereCartaoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbInserirCartao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInsereCartaoLayout.setVerticalGroup(
            panelInsereCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsereCartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInserirCartao)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelCartaoInserido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbCartaoInserido.setText("Cartao Inserido?");

        grupoCartao.add(rbSim);
        rbSim.setText("Sim");

        grupoCartao.add(rbNao);
        rbNao.setText("Não");

        javax.swing.GroupLayout panelCartaoInseridoLayout = new javax.swing.GroupLayout(panelCartaoInserido);
        panelCartaoInserido.setLayout(panelCartaoInseridoLayout);
        panelCartaoInseridoLayout.setHorizontalGroup(
            panelCartaoInseridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaoInseridoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCartaoInserido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCartaoInseridoLayout.setVerticalGroup(
            panelCartaoInseridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartaoInseridoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCartaoInseridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCartaoInserido)
                    .addComponent(rbSim)
                    .addComponent(rbNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCPF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grupoCPF.add(rbCPFNao);
        rbCPFNao.setText("Não");

        grupoCPF.add(rbCPFSim);
        rbCPFSim.setText("Sim");

        lbNotaFiscalPaulista.setText("Nota Fiscal Paulista?");

        lbCPF.setText("CPF");

        try {
            ftfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelCPFLayout = new javax.swing.GroupLayout(panelCPF);
        panelCPF.setLayout(panelCPFLayout);
        panelCPFLayout.setHorizontalGroup(
            panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCPFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCPFLayout.createSequentialGroup()
                        .addComponent(lbNotaFiscalPaulista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCPFSim))
                    .addGroup(panelCPFLayout.createSequentialGroup()
                        .addComponent(lbCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCPF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCPFNao)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelCPFLayout.setVerticalGroup(
            panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCPFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNotaFiscalPaulista)
                    .addComponent(rbCPFSim)
                    .addComponent(rbCPFNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(ftfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfirmarLayout = new javax.swing.GroupLayout(panelConfirmar);
        panelConfirmar.setLayout(panelConfirmarLayout);
        panelConfirmarLayout.setHorizontalGroup(
            panelConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfirmarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConfirmar)
                .addGap(38, 38, 38)
                .addComponent(btVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConfirmarLayout.setVerticalGroup(
            panelConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfirmarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar)
                    .addComponent(btVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCartaoInserido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInsereCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInsereCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCartaoInserido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void VerificadorCpf(){

        String cpf = ftfCPF.getText() ;

        String s1,s2,s3,s4,s5,s6,s7,s8,s9,confere = "";
        int n1,n2,n3,n4,n5,n6,n7,n8,n9,verificador1,verificador2;

        s1 = cpf.substring(0,1); n1 = Integer.parseInt(s1);
        s2 = cpf.substring(1,2); n2 = Integer.parseInt(s2);
        s3 = cpf.substring(2,3); n3 = Integer.parseInt(s3);
        s4 = cpf.substring(3,4); n4 = Integer.parseInt(s4);
        s5 = cpf.substring(4,5); n5 = Integer.parseInt(s5);
        s6 = cpf.substring(5,6); n6 = Integer.parseInt(s6);
        s7 = cpf.substring(6,7); n7 = Integer.parseInt(s7);
        s8 = cpf.substring(7,8); n8 = Integer.parseInt(s8);
        s9 = cpf.substring(8,9); n9 = Integer.parseInt(s9);

        verificador1 = (n1 * 10 + n2 * 9 + n3 * 8 + n4 * 7 + n5 * 6 + n6 * 5 + n7 * 4 + n8 * 3 + n9 * 2 );

        if((verificador1 % 11) < 2 ){
            verificador1 = 0;
        }else{
            verificador1 = 11 - (verificador1 % 11);
        }    

          verificador2 = (n1 * 11 + n2 * 10 + n3 * 9 + n4 * 8 + n5 * 7 + n6 * 6 + n7 * 5 + n8 * 4 + n9 * 3 + verificador1 * 2 );

            if((verificador2 % 11) < 2){
                verificador2 = 0;
            }else{
                verificador2 = 11 - (verificador2 % 11);
            }

            confere = (s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + verificador1 + "" + verificador2);

            if(confere.equals(cpf)){
                JOptionPane.showMessageDialog(null, "CPF VÁLIDO");
            }else{
                JOptionPane.showMessageDialog(null, "CPF INVÁLIDO");
            }
    }
    
    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if (rbSim.isSelected() == true){
            if (rbCPFSim.isSelected() == true){
                //VerificadorCpf(); 
            
                JOptionPane.showMessageDialog(null,"Dados confirmados e Cartao inserido!");
                       
                FrameSenha frameSenha = new FrameSenha();
                frameSenha.setVisible(true); //INSTANCIAR NOVO INSERE CARTAO
                
            }
            else if(rbCPFNao.isSelected() == true){
                JOptionPane.showMessageDialog(null,"Dados confirmados e Cartao inserido!");
                FrameSenha frameSenha = new FrameSenha();
                frameSenha.setVisible(true); //INSTANCIAR NOVO INSERE CARTAO
            }
            else{
                JOptionPane.showMessageDialog(null,"CPF invalido");
            }
        }
        else if(rbNao.isSelected() == true){
            JOptionPane.showMessageDialog(null,"Cartao nao inserido");
            
        } 
        else{
            JOptionPane.showMessageDialog(null,"Selecione se cartao esta inserido ou nao");
            
        }
        dispose();
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    //METODO PARA LIMPAR OS CAMPOS DO FRAME
    public void limparCamposFrame(){
        grupoCartao.clearSelection();
        grupoCPF.clearSelection();        
        ftfCPF.setText("");
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInsereCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInsereCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInsereCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInsereCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInsereCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JFormattedTextField ftfCPF;
    private javax.swing.ButtonGroup grupoCPF;
    private javax.swing.ButtonGroup grupoCartao;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCartaoInserido;
    private javax.swing.JLabel lbInserirCartao;
    private javax.swing.JLabel lbNotaFiscalPaulista;
    private javax.swing.JPanel panelCPF;
    private javax.swing.JPanel panelCartaoInserido;
    private javax.swing.JPanel panelConfirmar;
    private javax.swing.JPanel panelInsereCartao;
    private javax.swing.JRadioButton rbCPFNao;
    private javax.swing.JRadioButton rbCPFSim;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbSim;
    // End of variables declaration//GEN-END:variables
}
