/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class FrameValoresCombustiveis extends javax.swing.JFrame {
    FrameMenu frameMenu;
    ValoresCombustiveis valoresCombustiveis;
    
    
    /**
     * Creates new form FrameValoresCombustiveis
     */
    public FrameValoresCombustiveis() {
        initComponents();
        
    }

    
    public FrameValoresCombustiveis(FrameMenu frameMenu) {
        this.frameMenu = frameMenu;
        initComponents();
        ftfValorGasolinaComum.setText(String.valueOf(frameMenu.gasc));
        ftfValorGasolinaAditivada.setText(String.valueOf(frameMenu.gasa));
        ftfValorAlcool.setText(String.valueOf(frameMenu.al));
        ftfValorDiesel.setText(String.valueOf(frameMenu.di));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbValoresDosCombustiveis = new javax.swing.JLabel();
        lbValorGasolinaComum = new javax.swing.JLabel();
        lbValorGasolinaAditivada = new javax.swing.JLabel();
        lbValorAlcool = new javax.swing.JLabel();
        lbValorDiesel = new javax.swing.JLabel();
        ftfValorGasolinaComum = new javax.swing.JFormattedTextField();
        ftfValorGasolinaAditivada = new javax.swing.JFormattedTextField();
        ftfValorAlcool = new javax.swing.JFormattedTextField();
        ftfValorDiesel = new javax.swing.JFormattedTextField();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbValoresDosCombustiveis.setText("Valores dos combustiveis");

        lbValorGasolinaComum.setText("Gasolina Comum");

        lbValorGasolinaAditivada.setText("Gasolina Aditivada");

        lbValorAlcool.setText("Alcool");

        lbValorDiesel.setText("Diesel");

        ftfValorGasolinaComum.setEditable(false);
        ftfValorGasolinaComum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ftfValorGasolinaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfValorGasolinaComumActionPerformed(evt);
            }
        });

        ftfValorGasolinaAditivada.setEditable(false);

        ftfValorAlcool.setEditable(false);

        ftfValorDiesel.setEditable(false);

        btVoltar.setText("voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValoresDosCombustiveis)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValorGasolinaComum)
                                    .addComponent(lbValorGasolinaAditivada)
                                    .addComponent(lbValorAlcool)
                                    .addComponent(lbValorDiesel))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ftfValorGasolinaComum, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(ftfValorAlcool)
                                    .addComponent(ftfValorDiesel)
                                    .addComponent(ftfValorGasolinaAditivada)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btVoltar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbValoresDosCombustiveis)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorGasolinaComum)
                    .addComponent(ftfValorGasolinaComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorGasolinaAditivada)
                    .addComponent(ftfValorGasolinaAditivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorAlcool)
                    .addComponent(ftfValorAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorDiesel)
                    .addComponent(ftfValorDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void ftfValorGasolinaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfValorGasolinaComumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfValorGasolinaComumActionPerformed

    //Método para desabilitar campos do Frame
    public void desabilitarCamposFrame(){
        ftfValorGasolinaComum.setEditable(false);
        ftfValorGasolinaAditivada.setEditable(false);
        ftfValorAlcool.setEnabled(false);
        ftfValorDiesel.setEnabled(false); 
    }
    
    public void habilitarCamposFrame(){
        ftfValorGasolinaComum.setEditable(true);
        ftfValorGasolinaAditivada.setEditable(true);
        ftfValorAlcool.setEnabled(true);
        ftfValorDiesel.setEnabled(true); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameValoresCombustiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameValoresCombustiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameValoresCombustiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameValoresCombustiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameValoresCombustiveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JFormattedTextField ftfValorAlcool;
    private javax.swing.JFormattedTextField ftfValorDiesel;
    private javax.swing.JFormattedTextField ftfValorGasolinaAditivada;
    private javax.swing.JFormattedTextField ftfValorGasolinaComum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbValorAlcool;
    private javax.swing.JLabel lbValorDiesel;
    private javax.swing.JLabel lbValorGasolinaAditivada;
    private javax.swing.JLabel lbValorGasolinaComum;
    private javax.swing.JLabel lbValoresDosCombustiveis;
    // End of variables declaration//GEN-END:variables
}
