/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class FrameMenu extends javax.swing.JFrame {
    
    float gasc, gasa, al, di;

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        setExtendedState(MAXIMIZED_BOTH); //INICIAR MAXIMIZADO
        initComponents(); //INICIALIZA OS COMPONENTES DO FRAME
        setResizable(false); //NAO DEIXA REDIMENSIONAR
        
        gasc = (float) 3.10;
        gasa = (float) 3.50;
        al = (float) 2.20;
        di = (float) 2.80;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemIniciarMenuArquivo = new javax.swing.JMenuItem();
        itemConsultarMenuArquivo = new javax.swing.JMenuItem();
        itemListaMenuArquivo = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        itemValoresMenuEditar = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        intemSobreMenuAjuda = new javax.swing.JMenuItem();
        itemSairMenuAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArquivo.setText("Arquivo");
        menuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoActionPerformed(evt);
            }
        });

        itemIniciarMenuArquivo.setText("Iniciar");
        itemIniciarMenuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarMenuArquivoActionPerformed(evt);
            }
        });
        menuArquivo.add(itemIniciarMenuArquivo);

        itemConsultarMenuArquivo.setText("Consultar");
        itemConsultarMenuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarMenuArquivoActionPerformed(evt);
            }
        });
        menuArquivo.add(itemConsultarMenuArquivo);

        itemListaMenuArquivo.setText("Lista");
        itemListaMenuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaMenuArquivoActionPerformed(evt);
            }
        });
        menuArquivo.add(itemListaMenuArquivo);

        barraMenuPrincipal.add(menuArquivo);

        menuEditar.setText("Editar");

        itemValoresMenuEditar.setText("Valores");
        itemValoresMenuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemValoresMenuEditarActionPerformed(evt);
            }
        });
        menuEditar.add(itemValoresMenuEditar);

        barraMenuPrincipal.add(menuEditar);

        menuAjuda.setText("Ajuda");

        intemSobreMenuAjuda.setText("Sobre");
        intemSobreMenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemSobreMenuAjudaActionPerformed(evt);
            }
        });
        menuAjuda.add(intemSobreMenuAjuda);

        itemSairMenuAjuda.setText("Sair");
        itemSairMenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairMenuAjudaActionPerformed(evt);
            }
        });
        menuAjuda.add(itemSairMenuAjuda);

        barraMenuPrincipal.add(menuAjuda);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemIniciarMenuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarMenuArquivoActionPerformed
        FrameAbastecimento frameAbastecimento = new FrameAbastecimento(this);
        frameAbastecimento.setVisible(true); //INSTANCIAR NOVO ValorLitragem
    }//GEN-LAST:event_itemIniciarMenuArquivoActionPerformed

    private void itemSairMenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairMenuAjudaActionPerformed
        System.exit(0); //SAIR DA APLICAÇÃO
    }//GEN-LAST:event_itemSairMenuAjudaActionPerformed

    private void itemValoresMenuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemValoresMenuEditarActionPerformed
        FrameEditarValores frameEditarValores = new FrameEditarValores(this);
        frameEditarValores.setVisible(true); // Instanciar novo EditarValores
    }//GEN-LAST:event_itemValoresMenuEditarActionPerformed

    private void menuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoActionPerformed
        
    }//GEN-LAST:event_menuArquivoActionPerformed

    private void itemConsultarMenuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarMenuArquivoActionPerformed
        FrameValoresCombustiveis frameValoresCombustiveis = new FrameValoresCombustiveis(this);
        frameValoresCombustiveis.setVisible(true); // Instanciar novo EditarValores
    }//GEN-LAST:event_itemConsultarMenuArquivoActionPerformed

    private void intemSobreMenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemSobreMenuAjudaActionPerformed
        FrameSobre frameSobre = new FrameSobre();
        frameSobre.setVisible(true); //INSTANCIAR NOVO SOBRE
    }//GEN-LAST:event_intemSobreMenuAjudaActionPerformed

    private void itemListaMenuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaMenuArquivoActionPerformed
        FrameLista frameLista = new FrameLista();
        frameLista.setVisible(true);//INSTANCIAR NOVO LISTA
    }//GEN-LAST:event_itemListaMenuArquivoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JMenuItem intemSobreMenuAjuda;
    private javax.swing.JMenuItem itemConsultarMenuArquivo;
    private javax.swing.JMenuItem itemIniciarMenuArquivo;
    private javax.swing.JMenuItem itemListaMenuArquivo;
    private javax.swing.JMenuItem itemSairMenuAjuda;
    private javax.swing.JMenuItem itemValoresMenuEditar;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEditar;
    // End of variables declaration//GEN-END:variables
}
