import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class FrameAbastecimento extends javax.swing.JFrame {
    FrameMenu frameMenu;
    Abastecimento abastecimento;
    ArrayList <Abastecimento> abastecimentos = new ArrayList();
    
    //ArrayList <Abastecimento> abastecimentos = new ArrayList();
    /**
     * Creates new form FrameAbastecimento
     */
    public FrameAbastecimento() {
        initComponents();
        setResizable(false);  //NAO DEIXA REDIMENSIONAR
        setLocation(220, 200);
        
    }
    
    public FrameAbastecimento(FrameMenu frameMenu) {
        this.frameMenu = frameMenu;
        initComponents();
        setResizable(false);  //NAO DEIXA REDIMENSIONAR
        setLocation(220, 200);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoCombustivel = new javax.swing.ButtonGroup();
        grupoTipoCartao = new javax.swing.ButtonGroup();
        panelValorLitragem = new javax.swing.JPanel();
        lbValorLitragem = new javax.swing.JLabel();
        lbIgual = new javax.swing.JLabel();
        lbAutoAbastecimento = new javax.swing.JLabel();
        rbGasolinaComum = new javax.swing.JRadioButton();
        rbGasolinaAditivada = new javax.swing.JRadioButton();
        rbAlcool = new javax.swing.JRadioButton();
        rbDiesel = new javax.swing.JRadioButton();
        ftfValor = new javax.swing.JFormattedTextField();
        ftfLitragem = new javax.swing.JFormattedTextField();
        lbRs = new javax.swing.JLabel();
        lbLitros = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        lbTipo = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        lbRsL = new javax.swing.JLabel();
        ftfValorLitro = new javax.swing.JFormattedTextField();
        panelCreditoDebito = new javax.swing.JPanel();
        rbCredito = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        lbCreditoDebito = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelValorLitragem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbValorLitragem.setText("Valor ou Litragem?");

        lbIgual.setText("=");

        lbAutoAbastecimento.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbAutoAbastecimento.setText("Auto Abastecimento");

        grupoTipoCombustivel.add(rbGasolinaComum);
        rbGasolinaComum.setText("Gasolina Comum");
        rbGasolinaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGasolinaComumActionPerformed(evt);
            }
        });

        grupoTipoCombustivel.add(rbGasolinaAditivada);
        rbGasolinaAditivada.setText("Gasolina Aditivada");
        rbGasolinaAditivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGasolinaAditivadaActionPerformed(evt);
            }
        });

        grupoTipoCombustivel.add(rbAlcool);
        rbAlcool.setText("Álcool");
        rbAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlcoolActionPerformed(evt);
            }
        });

        grupoTipoCombustivel.add(rbDiesel);
        rbDiesel.setText("Diesel");
        rbDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDieselActionPerformed(evt);
            }
        });

        ftfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ftfValor.setText("0");
        ftfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfValorActionPerformed(evt);
            }
        });

        ftfLitragem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ftfLitragem.setText("0");
        ftfLitragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfLitragemActionPerformed(evt);
            }
        });

        lbRs.setText("R$");

        lbLitros.setText("Litros");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbTipo.setText("Tipo");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lbRsL.setText("R$/L");

        ftfValorLitro.setEditable(false);

        javax.swing.GroupLayout panelValorLitragemLayout = new javax.swing.GroupLayout(panelValorLitragem);
        panelValorLitragem.setLayout(panelValorLitragemLayout);
        panelValorLitragemLayout.setHorizontalGroup(
            panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValorLitragemLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbAutoAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelValorLitragemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                                .addComponent(lbRs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfLitragem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                                .addComponent(lbTipo)
                                .addGap(18, 18, 18)
                                .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbGasolinaComum)
                                    .addComponent(rbGasolinaAditivada))))
                        .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbLitros)
                                .addGap(18, 18, 18)
                                .addComponent(btCalcular))
                            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbDiesel)
                                    .addComponent(rbAlcool))))
                        .addGap(22, 22, 22)
                        .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLimpar)
                            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                                .addComponent(ftfValorLitro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbRsL))))
                    .addGroup(panelValorLitragemLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbValorLitragem)))
                .addGap(30, 30, 30))
        );
        panelValorLitragemLayout.setVerticalGroup(
            panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLitragemLayout.createSequentialGroup()
                .addComponent(lbAutoAbastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGasolinaComum)
                    .addComponent(rbAlcool)
                    .addComponent(lbTipo)
                    .addComponent(lbRsL)
                    .addComponent(ftfValorLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGasolinaAditivada)
                    .addComponent(rbDiesel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValorLitragem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelValorLitragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIgual)
                    .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfLitragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRs)
                    .addComponent(lbLitros)
                    .addComponent(btCalcular)
                    .addComponent(btLimpar))
                .addGap(99, 99, 99))
        );

        panelCreditoDebito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grupoTipoCartao.add(rbCredito);
        rbCredito.setText("Credito");

        grupoTipoCartao.add(rbDebito);
        rbDebito.setText("Debito");

        lbCreditoDebito.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbCreditoDebito.setText("Crédito ou Debito?");

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreditoDebitoLayout = new javax.swing.GroupLayout(panelCreditoDebito);
        panelCreditoDebito.setLayout(panelCreditoDebitoLayout);
        panelCreditoDebitoLayout.setHorizontalGroup(
            panelCreditoDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditoDebitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreditoDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreditoDebitoLayout.createSequentialGroup()
                        .addComponent(btConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCreditoDebitoLayout.createSequentialGroup()
                        .addComponent(lbCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCredito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDebito)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCreditoDebitoLayout.setVerticalGroup(
            panelCreditoDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditoDebitoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelCreditoDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCredito)
                    .addComponent(rbDebito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCreditoDebitoLayout.createSequentialGroup()
                .addComponent(lbCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCreditoDebitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar)
                    .addComponent(btListar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelValorLitragem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCreditoDebito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelValorLitragem, javax.swing.GroupLayout.PREFERRED_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        abastecimento = new Abastecimento();
        float valor1, valor2;
        valor1 = 0;
        valor2 = 0;
        
        valor1 = Float.parseFloat(ftfValor.getText());
        valor2 = Float.parseFloat(ftfLitragem.getText());
               
        if (rbGasolinaComum.isSelected() && valor1 != 0) { 
            valor2 = (valor1 / frameMenu.gasc);
            //ftfLitragem.setValue(valor2);
            ftfLitragem.setText(String.valueOf(valor2));
            desabilitarCamposFrame();
        }
        else if (rbGasolinaComum.isSelected() && valor2 != 0){
            valor1 = (valor2 * frameMenu.gasc);
            ftfValor.setText(String.valueOf(valor1));
            desabilitarCamposFrame();
        }
        else if (rbGasolinaAditivada.isSelected() && valor1 != 0 ) {
            valor2 = (valor1 / frameMenu.gasa);
            ftfLitragem.setText(String.valueOf(valor2));
            desabilitarCamposFrame();
        }
        else if (rbGasolinaAditivada.isSelected() && valor2 != 0){
            valor1 = (valor2 * frameMenu.gasa);
            ftfValor.setText(String.valueOf(valor1));
            desabilitarCamposFrame();
        }
        else if (rbAlcool.isSelected() && valor1 != 0) {
            valor2 = (valor1 / frameMenu.al);
            ftfLitragem.setText(String.valueOf(valor2));
            desabilitarCamposFrame();
        }
        else if (rbAlcool.isSelected() && valor2 != 0){
            valor1 = (valor2 * frameMenu.al);
            ftfValor.setText(String.valueOf(valor1));
            desabilitarCamposFrame();
        }
        else if (rbDiesel.isSelected() && valor1 != 0) {
            valor2 = (valor1 / frameMenu.di);
            ftfLitragem.setText(String.valueOf(valor2));
            desabilitarCamposFrame();
        }
        else {
            valor1 = (valor2 * frameMenu.di);
            ftfValor.setText(String.valueOf(valor1));
            desabilitarCamposFrame();
        }
                
    }//GEN-LAST:event_btCalcularActionPerformed
   
    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        float campoValor;
        campoValor = Float.parseFloat(ftfValor.getText());
        if (campoValor != 0){
            if (rbCredito.isSelected() == true){
                FrameInsereCartao frameInsereCartao = new FrameInsereCartao();
                frameInsereCartao.setVisible(true); //INSTANCIAR NOVO INSERE CARTAO]
                JOptionPane.showMessageDialog(null,"Credito selecionado. Dados confirmados!");
            }
            else if(rbDebito.isSelected() == true){
                FrameInsereCartao frameInsereCartao = new FrameInsereCartao();
                frameInsereCartao.setVisible(true); //INSTANCIAR NOVO INSERE CARTAO]
                JOptionPane.showMessageDialog(null,"Debito selecionado. Dados confirmados!");
            }
            else{
                JOptionPane.showMessageDialog(null,"Selecione tipo de cartao!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Calcule o valor ou a quantidade de Litros!");
        }
        
        abastecimento = new Abastecimento();
        abastecimento.setValor(Float.parseFloat(ftfValor.getText())); 
        abastecimento.setLitragem(Float.parseFloat(ftfLitragem.getText())); 
        abastecimento.setTipo(rbCredito.isSelected()?"Credito":"Debito");
              
        if(inserirNovoAbastecimento(abastecimento)){
            JOptionPane.showMessageDialog(null,"Abastecimento salvo com sucesso!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Não foi possível salvar o abastecimento!");
        }
        limparCamposFrame(); 
    }//GEN-LAST:event_btConfirmarActionPerformed

    //Método para adicionar um novo cliente no Array
    public boolean inserirNovoAbastecimento(Abastecimento abastecimento){
        return abastecimentos.add(abastecimento);       
    }

    //Metodo para buscar valores pelo valor  *************
    public Abastecimento buscarAbastecimento(float valor){
            Abastecimento abastecimento = new Abastecimento();
            for(int i=0; i < abastecimentos.size(); i++)
                if (abastecimentos.get(i).getAbastecimento().equals(abastecimento))
                    return Abastecimentos.get(i);
            
            return abastecimento;  
    }
    
    
    
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed

        String strTexto ="";

        //Alimenta a variavel com os nomes
        for(int i=0;i < abastecimentos.size(); i++)
        strTexto += abastecimentos.get(i).getValor() + "\n";

        //Abre a tela e exibe o texto
        FrameLista frameLista = new FrameLista();
        frameLista.setVisible(true);
        frameLista.setTextArea(strTexto);                                      

    }//GEN-LAST:event_btListarActionPerformed

    private void ftfLitragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfLitragemActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_ftfLitragemActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCamposFrame();
        habilitarCamposFrame();
    }//GEN-LAST:event_btLimparActionPerformed

    private void ftfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfValorActionPerformed

    private void rbGasolinaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGasolinaComumActionPerformed
        mostraValor();
    }//GEN-LAST:event_rbGasolinaComumActionPerformed

    private void rbAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlcoolActionPerformed
        mostraValor();
    }//GEN-LAST:event_rbAlcoolActionPerformed

    private void rbGasolinaAditivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGasolinaAditivadaActionPerformed
        mostraValor();
    }//GEN-LAST:event_rbGasolinaAditivadaActionPerformed

    private void rbDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDieselActionPerformed
        mostraValor();
    }//GEN-LAST:event_rbDieselActionPerformed

       //METODO PARA DESABILITAR CAMPOS DO FRAME
    public void desabilitarCamposFrame(){    
        ftfLitragem.setEnabled(false);
        ftfValor.setEnabled(false);
    }
    
    //METODO PARA HABILITAR CAMPOS DO FRAME
    public void habilitarCamposFrame(){    
        ftfValor.setEnabled(true);
        ftfLitragem.setEnabled(true);
    }
    
    //METODO PARA LIMPAR OS CAMPOS DO FRAME
    public void limparCamposFrame(){
        ftfValor.setText("0");
        ftfLitragem.setText("0");
        grupoTipoCombustivel.clearSelection();
        grupoTipoCartao.clearSelection();
    }
    
    //Metodo para indicar valor do combustivel selecionado
    public void mostraValor(){
            float valorLitro;
            if (rbGasolinaComum.isSelected()) {
                valorLitro = frameMenu.gasa;
                ftfValorLitro.setText(String.valueOf(valorLitro));
            }
            else if (rbGasolinaAditivada.isSelected()) {
                valorLitro = frameMenu.gasc;
                ftfValorLitro.setText(String.valueOf(valorLitro));
            }
            else if (rbAlcool.isSelected()) {
                valorLitro = frameMenu.al;
                ftfValorLitro.setText(String.valueOf(valorLitro));
            }
            else if (rbDiesel.isSelected()) {
                valorLitro = frameMenu.di;
                ftfValorLitro.setText(String.valueOf(valorLitro));
            }
            else {
            
            }
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAbastecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAbastecimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btListar;
    private javax.swing.JFormattedTextField ftfLitragem;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JFormattedTextField ftfValorLitro;
    private javax.swing.ButtonGroup grupoTipoCartao;
    private javax.swing.ButtonGroup grupoTipoCombustivel;
    private javax.swing.JLabel lbAutoAbastecimento;
    private javax.swing.JLabel lbCreditoDebito;
    private javax.swing.JLabel lbIgual;
    private javax.swing.JLabel lbLitros;
    private javax.swing.JLabel lbRs;
    private javax.swing.JLabel lbRsL;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbValorLitragem;
    private javax.swing.JPanel panelCreditoDebito;
    private javax.swing.JPanel panelValorLitragem;
    private javax.swing.JRadioButton rbAlcool;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JRadioButton rbDiesel;
    private javax.swing.JRadioButton rbGasolinaAditivada;
    private javax.swing.JRadioButton rbGasolinaComum;
    // End of variables declaration//GEN-END:variables
}
